include("$ENV{VITASDK}/share/vita.toolchain.cmake")

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS}   -marm" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -marm" CACHE STRING "" FORCE)

set(PX_BUILD_DLL        OFF CACHE BOOL "" FORCE)
set(PX_INCLUDE_SPDLOG   OFF CACHE BOOL "" FORCE)
set(PX_INCLUDE_GLFW     OFF CACHE BOOL "" FORCE)
set(PX_INCLUDE_VULKAN   OFF CACHE BOOL "" FORCE)
set(PX_INCLUDE_IMGUI   OFF CACHE BOOL "" FORCE)
set(PX_INCLUDE_OPENGL   ON CACHE BOOL "" FORCE)
set(PX_INCLUDE_GLAD     OFF CACHE BOOL "" FORCE)
set(PX_INCLUDE_VITASDK  ON CACHE BOOL "" FORCE)

set(VITA_TITLEID  "PRDX00001" CACHE STRING "")
set(VITA_VERSION  "01.00"    CACHE STRING "")
set(VITA_APP_NAME "Runtime"  CACHE STRING "")
set(VITA_MKSFOEX_FLAGS "${VITA_MKSFOEX_FLAGS} -d PARENTAL_LEVEL=1")
